channels:
- menpo
dependencies:
- python=2.7
- ffmpeg
- yaml
- pip
- pip:
  - PySide
  - git+https://github.com/pyqt/python-qt5.git#python-qt5
- git:
  - https://github.com/tokejepsen/filelink.git@01c782e4ce8043914cc09908392747954f5284b1
  - https://github.com/pyblish/pyblish-base.git@20fc70471970cdd80471f0d1ed68fa35864aea83
  - https://github.com/pyblish/pyblish-nuke.git@f9f593341128aaad11b0065cc20569694b83ba0c
  - https://github.com/pyblish/pyblish-maya.git@b81e6edd67e9969348a133c8a6e630ab92fd6c3f
  - https://github.com/pyblish/pyblish-houdini.git@88b189a82fd6b757aa7557c1c490b97e740154a5
  - https://github.com/pyblish/pyblish-lite.git@5c9bd64bc649a1537f79682866a37258639b66a0
  - https://github.com/pyblish/pyblish-qml.git@da37f2f04dadbe2837cbcb362790e40bfcf13eda
  - https://github.com/pyblish/pyblish-houdini.git@88b189a82fd6b757aa7557c1c490b97e740154a5
  - https://github.com/pyblish/pyblish-nukestudio.git@225b2af344468fa43c51a14f71a512b8a317cb48
  - https://github.com/pyblish/pyblish-deadline.git@10c1a4ff3fd4f44dc7ff34f104fa41a62adb3091
  - https://github.com/pyblish/pyblish-ftrack.git@d21d185cc327bc360bb8d2b93305f64218bdb747
  - https://bitbucket.org/ftrack/ftrack-python-legacy-api.git@97cb35a6ae98958f95e61a7925701d9e8eea375d
  - https://bitbucket.org/ftrack/ftrack-connect.git@88633ab298799eccdfddd0b897b7615bac1aa952
  - https://bitbucket.org/ftrack/ftrack-connect-foundry.git@7cf86f01faf983c6f094dd86cda8ecdd7417cf3e
  - https://bitbucket.org/ftrack/ftrack-connect-nuke.git@f9f593341128aaad11b0065cc20569694b83ba0c
  - https://bitbucket.org/ftrack/ftrack-connect-nuke-studio.git@d97733435037c54a7d091df3f4ecafef11d41b03
  - https://bitbucket.org/ftrack/ftrack-connect-maya.git@23c7ffa6ee97e8032180246a585428d09c474ea3
  - https://bitbucket.org/ftrack/ftrack-connect-rv.git@a1810c5309312c3aa4aa7855beeda44ee798c279
  - https://bitbucket.org/ftrack/QtExt.git@f88d1db8d5b7a0f5162f29a0701166d3be24fd19
  - https://github.com/kredencz/pyblish-kredenc.git@d57f290ef7babadf057cd26859f4572d04d2ab20
  - https://github.com/kredencz/ftrack-kredenc-hooks.git@f433627a88222b2404a6f0ed67d0d04b8fd8acb9
  - https://github.com/mkolar/ftrack-hooks.git@072a6ea13d86a76b02f9e75c9dffdc3ee503671c
  - https://github.com/mkolar/lucidity.git@13f8efeaf99157239984bba79d31620c5338bcdb
  - https://github.com/mkolar/maya-capture.git@01ef86333694cd528293c855ac39c18e84bbffcf
  - https://github.com/BigRoy/maya-capture-gui.git@a9224af58026a5da1c7e40c1c6ae80abf6f8c665
  - https://bitbucket.org/milankolar/ftrack-events-environment.git@cc1497a8d59fc267a13f0bd53a842fb56e10dabb
  - https://github.com/tokejepsen/ftrack-connect-environment.git:
    - python $REPO_PATH/environment.py
  - https://github.com/kredencz/kredenc-environment.git:
    - python $REPO_PATH/environment.py
    - python -m ftrack_connect
name: kredenc-environment
