channels:
- menpo
dependencies:
- python=2.7
- ffmpeg
- pip
- pip:
  - PySide
  - clique
  - lucidity
  - pyperclip
  - arrow
  - ftrack-python-api
- git:
  - https://github.com/abstractfactory/maya-capture.git@bdea21ad0cfa008b70d3419438687faf535e85b7
  - https://github.com/kredencz/pyblish-kredenc.git
  - https://github.com/mkolar/ftrack-hooks.git
  - https://github.com/mkolar/maya-capture-gui.git
  - https://github.com/pyblish/pyblish-base.git
  - https://github.com/pyblish/pyblish-maya.git
  - https://github.com/pyblish/pyblish-nuke.git
  - https://github.com/pyblish/pyblish-lite.git
  - https://github.com/pyblish/pyblish-nukestudio.git
  - https://github.com/pyblish/pyblish-deadline.git
  - https://github.com/pyblish/pyblish-ftrack.git
  - https://github.com/pyblish/pyblish-houdini.git
  - https://bitbucket.org/ftrack/ftrack-python-legacy-api.git
  - https://bitbucket.org/ftrack/ftrack-connect.git
  - https://bitbucket.org/ftrack/ftrack-connect-maya.git
  - https://bitbucket.org/ftrack/ftrack-connect-nuke.git
  - https://bitbucket.org/ftrack/ftrack-connect-rv.git
  - https://bitbucket.org/ftrack/ftrack-connect-nuke-studio.git
  - https://github.com/tokejepsen/ftrack-connect-environment.git:
    - python $REPO_PATH/environment.py
    - python -m ftrack_connect
name: kredenc-environment
