paths:

    # =================
    # SHOTS WORKFLOW
    # ==================

    # Shot folders

    shot:
        pattern: '{ft_hierarchy}'


    # Task folders

    shot.task.publish:
        pattern: '{@shot}/publish'
    shot.task.work:
        pattern: '{@shot}/work/{Task.name}'
    shot.render:
        pattern: '{@shot}/publish/render/{Task.name}'


    # iles

    shot.sceneBase:
        pattern: '{Project.code}_{Shot.name}_{Task.name}_{version}'
    shot.publish.base:
        pattern: '{Project.code}_{Shot.name}_{family}_{item}_{version}{subset}'
    shot.publish.basemaster:
        pattern: '{Project.code}_{Shot.name}_{family}_{item}{subset}'


    shot.work.scene:
        pattern: '{@shot.task.work}/{@shot.sceneBase}.{ext}'
    shot.publish.scene:
        pattern: '{@shot.task.publish}/scenes/{Task.name}/{@shot.sceneBase}.{ext}'


    shot.publish.item:
        pattern: '{@shot.task.publish}/{family}/{item}/{version}/{@shot.publish.base}.{ext}'
    shot.publish.master:
        pattern: '{@shot.task.publish}/{family}/{item}/{@shot.publish.basemaster}.{ext}'

    shot.render.folder:
        pattern: '{@shot.render}/{Task.name}/{renderlayer}/{version}'
    shot.render.file:
        pattern: '{@shot.render.folder}/{@shot.sceneBase}_{renderlayer}.{seq}.exr'
